version: '3.4'

services:
  appstatus:
    image: appstatus
    build: .
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://mongodb:27017/appstatus
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: